package tasks.oct_04_2024;

public class Person_Objects {
    public static void main(String[] args) {
        System.out.println("Object 1:");
        Person_BluePrint person = new Person_BluePrint();
        System.out.println("Objects with parameters:");
        Person_BluePrint person1 = new Person_BluePrint(1,"Priya","Female","14Nov1988",35,9876543210L,"AutomationEngineer",70000);
        System.out.println("Roll No: " + person1.rollNo);
        System.out.println("Name : "+ person1.name);
        System.out.println("Gender : " + person1.gender);
        System.out.println("DOB : "+ person1.dob);
        System.out.println("Age : " + person1.age);
        System.out.println("Phone Number : " + person1.phNo);
        System.out.println("Occupation : " + person1.occupation);
        System.out.println("Salary : " + person1.salary);
        person1.walk();
        person1.talk("English");
        String hobby = person1.sleep();
        System.out.println(hobby);
        String where = person1.place("India");
        System.out.println("Place : " + where);
        Person_BluePrint person2 = new Person_BluePrint(2,"Pranu","Male","07AOct2015",9,9836543210L,"Studying 3rd std",10000);
        System.out.println("Roll No: " + person2.rollNo);
        System.out.println("Name : "+ person2.name);
        System.out.println("Gender : " + person2.gender);
        System.out.println("DOB : "+ person2.dob);
        System.out.println("Age : " + person2.age);
        System.out.println("Phone Number : " + person2.phNo);
        System.out.println("Occupation : " + person2.occupation);
        System.out.println("Salary : " + person2.salary);
        person2.walk();
        person2.talk("Swedish");
        String hobby1 = person2.sleep();
        System.out.println(hobby1);
        String where1 = person2.place("Sweden");
        System.out.println("Place : " + where1);
        Person_BluePrint person3 = new Person_BluePrint(3,"Shan","Male","30May1985",39,9836643210L,"AmazonOpsEngineer",90000);
        System.out.println("Roll No: " + person3.rollNo);
        System.out.println("Name : "+ person3.name);
        System.out.println("Gender : " + person3.gender);
        System.out.println("DOB : "+ person3.dob);
        System.out.println("Age : " + person3.age);
        System.out.println("Phone Number : " + person3.phNo);
        System.out.println("Occupation : " + person3.occupation);
        System.out.println("Salary : " + person3.salary);
        person3.walk();
        person3.talk("German");
        String hobby2 = person3.sleep();
        System.out.println(hobby2);
        String where2 = person3.place("Germany");
        System.out.println("Place : " + where2);
        Person_BluePrint person4 = new Person_BluePrint(4,"Ashwin","Male","23June2006",18,9836648210L,"1st Year Engineering",30000);
        System.out.println("Roll No: " + person4.rollNo);
        System.out.println("Name : "+ person4.name);
        System.out.println("Gender : " + person4.gender);
        System.out.println("DOB : "+ person4.dob);
        System.out.println("Age : " + person4.age);
        System.out.println("Phone Number : " + person4.phNo);
        System.out.println("Occupation : " + person4.occupation);
        System.out.println("Salary : " + person4.salary);
        person4.walk();
        person4.talk("Norwegian");
        String hobby3 = person4.sleep();
        System.out.println(hobby3);
        String where3 = person4.place("Norway");
        System.out.println("Place : " + where3);
        Person_BluePrint person5 = new Person_BluePrint(5,"Ashmi","Female","18Oct2013",11,9836843210L,"Studying 6th std",20000);
        System.out.println("Roll No: " + person5.rollNo);
        System.out.println("Name : "+ person5.name);
        System.out.println("Gender : " + person5.gender);
        System.out.println("DOB : "+ person5.dob);
        System.out.println("Age : " + person5.age);
        System.out.println("Phone Number : " + person5.phNo);
        System.out.println("Occupation : " + person5.occupation);
        System.out.println("Salary : " + person5.salary);
        person5.walk();
        person5.talk("Japanis");
        String hobby4 = person5.sleep();
        System.out.println(hobby4);
        String where4 = person5.place("Japan");
        System.out.println("Place : " + where4);
    }
}
